### ISSUE TITLE
Will be supported fullcalendar v4 ? 

### ISSUE THREAD

**Issue by matteo-cerioni** [Edofre/yii2-fullcalendar#18]
From [Fullcalendar Blog Article](https://fullcalendar.io/blog/2019/03/v4-officially-released)
A year after the project first began, version 4 is finally released. A tremendous amount of work went into it. To summarize the advancements over v3:

- jQuery has been removed
- Moment has been removed and time zones have been rethought
- The API is more modern
- Functionality is broken into lightweight plugins
- Plugins have been added for recurring events, Moment, and Luxon
- Touch interactions and scrolling work better
- Lots of internal refactoring that has already made development much faster

[V4 Release Notes and Upgrade Guide](https://fullcalendar.io/docs/upgrading-from-v3)

**Comment by Edofre** [comment]
Hey @MattiCerio, unfortunately I will not be supporting version v4. I'm not using the fullcalendar in my projects anymore so I have no incentive to work on it.
