### ISSUE TITLE
Invalid path to the language file

### ISSUE THREAD

**Issue by s1lver** [Edofre/yii2-fullcalendar#4]
In some cases, there is no true definition of the path to the language file. 

Some steps:

1.  Add to composer required section  `"edofre/yii2-fullcalendar": "@dev",`
2.  Installing the vendor package
3.  Including the fullcalendar widget etc.
4. Put the error message and do not translate message

> Failed to load resource: the server responded with a status of 404 (Not Found)  .../assets/1870ec20/lang-all.js

**Comment by Edofre** [comment]
You're right, Fullcalendar 3.0 changed the names/locations of the language files. Working on a fix now.

**Comment by Edofre** [comment]
@s1lver If you update your composer.json to include version: "V1.0.4" it should be fixed. Thanks for letting me know!

**Comment by s1lver** [comment]
Ok, thanks!
